[mypy]
python_version = 3.13
mypy_path = tools/lib
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_any_unimported = False
check_untyped_defs = True
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
ignore_missing_imports = False
