"""Document invariant checks (P3) — capability facade.

Re-exports everything from ``modules.shared.src.doc_pack`` so callers that
already import from ``modules.check.src.capabilities_doc_pack`` keep working
through the refactor without a second import-swap pass.
"""
from __future__ import annotations

from modules.shared.src.utility_doc_pack import (
    ERROR,
    WARN,
    _ALWAYS_GATING,
    _COMMANDS_HEADINGS,
    _OWNERSHIP_SKIP_DIRS,
    _SECTION_ALIASES,
    _SKIP_PARTS,
    MASTER_ONLY_SECTIONS,
    REQUIRED_SECTIONS,
    DocFinding,
    _Section,
    Table,
    _cells,
    _ci_text,
    _is_resolvable,
    _lines,
    _missing_sections,
    _norm,
    _owns_finding,
    _read,
    _secret_value,
    _state_is_known,
    as_strict,
    audit_docs,
    blank_fenced,
    check_backlog_rows,
    check_command_drift,
    check_fr_ids,
    check_hygiene,
    check_length_budget,
    check_links,
    check_scenarios,
    check_spec_pairing,
    check_spec_status_leak,
    check_state_vocabulary,
    errors_only,
    find_section,
    iter_doc_files,
    md_links,
    parse_tables,
    sections,
    warnings_only,
)

__all__ = [
    "ERROR",
    "WARN",
    "_ALWAYS_GATING",
    "_COMMANDS_HEADINGS",
    "_OWNERSHIP_SKIP_DIRS",
    "_SECTION_ALIASES",
    "_SKIP_PARTS",
    "MASTER_ONLY_SECTIONS",
    "REQUIRED_SECTIONS",
    "DocFinding",
    "_Section",
    "Table",
    "_cells",
    "_ci_text",
    "_is_resolvable",
    "_lines",
    "_missing_sections",
    "_norm",
    "_owns_finding",
    "_read",
    "_secret_value",
    "_state_is_known",
    "as_strict",
    "audit_docs",
    "blank_fenced",
    "check_backlog_rows",
    "check_command_drift",
    "check_fr_ids",
    "check_hygiene",
    "check_length_budget",
    "check_links",
    "check_scenarios",
    "check_spec_pairing",
    "check_spec_status_leak",
    "check_state_vocabulary",
    "errors_only",
    "find_section",
    "iter_doc_files",
    "md_links",
    "parse_tables",
    "sections",
    "warnings_only",
]
